### ISSUE TITLE
Question about installing cmi's

### ISSUE THREAD

**Issue by Kakadu** [ocsigen/eliom-widgets#1]
Yesterday I have reached problem while linking against eliom-widgets.

```
Error: The files /home/kakadu/.opam/4.00.1/lib/eliom/server/eliom_pervasives.cmi
       and /home/kakadu/.opam/4.00.1/lib/eliom-widgets/eliom_widgets.cmi
       make inconsistent assumptions over interface Eliom_common
```

There is a possibility that it caused by suspicious eliom-widgets installation process

```
ocaml setup.ml -install 
....
Installed /home/kakadu/.opam/4.00.1/lib/eliom-widgets/eliom_widgets.cmi
Installed /home/kakadu/.opam/4.00.1/lib/eliom-widgets/eliom_widgets.cmx
Installed /home/kakadu/.opam/4.00.1/lib/eliom-widgets/editable.cmx
......
ocamlfind: [WARNING] Overwriting file /home/kakadu/.opam/4.00.1/lib/eliom-widgets/eliom_widgets.cmi
Installed /home/kakadu/.opam/4.00.1/lib/eliom-widgets/eliom_widgets.cmi
ocamlfind: [WARNING] Overwriting file /home/kakadu/.opam/4.00.1/lib/eliom-widgets/eliom_widgets.cmx
Installed /home/kakadu/.opam/4.00.1/lib/eliom-widgets/eliom_widgets.cmx
ocamlfind: [WARNING] Overwriting file /home/kakadu/.opam/4.00.1/lib/eliom-widgets/editable.cmx
Installed /home/kakadu/.opam/4.00.1/lib/eliom-widgets/editable.cmx
....
```

These files are overwritten because we have them twice: for client and server sides. Is it OK?

**Comment by ccharly** [comment]
Hi,

since we're using a Makefile instead of OASIS, this issue has been fixed ! :)

**Comment by Drup** [comment]
As a side note, we have a feature request for oasis that will solve the problem (see [here](https://forge.ocamlcore.org/tracker/?func=detail&atid=294&aid=1305&group_id=54)) and we may switch back to oasis when this is done.

**Comment by Kakadu** [comment]
Btw, have you tried this ocamlbuild plugin :
https://github.com/sergezloto/eliom-ocamlbuild/ 
?

**Comment by Drup** [comment]
I use [jpdplaix's one](https://bitbucket.org/deplai_j/ocamlbuild_eliom), which works better IMO, but that's just the build part, It doesn't solve the instalation problem.
